vim.o.termguicolors = true

-- Reset highlighting.
vim.cmd.highlight('clear')
if vim.fn.exists('syntax_on') == 1 then vim.cmd.syntax('reset') end

vim.g.colors_name = 'nord'

-- Nord base palette, plus a few local UI accents.
local c = {
  none = 'NONE',
  nord0 = '#2E3440',
  nord1 = '#3B4252',
  nord2 = '#434C5E',
  nord3 = '#4C566A',
  nord3_bright = '#616E88',
  inlay_hint = '#6F5F73',
  nord4 = '#D8DEE9',
  nord5 = '#E5E9F0',
  nord6 = '#ECEFF4',
  nord7 = '#8FBCBB',
  nord8 = '#88C0D0',
  nord9 = '#81A1C1',
  nord10 = '#5E81AC',
  nord11 = '#BF616A',
  nord12 = '#D08770',
  nord13 = '#EBCB8B',
  nord14 = '#A3BE8C',
  nord15 = '#B48EAD',
}

local set = function(group, spec) vim.api.nvim_set_hl(0, group, spec) end

-- Terminal ANSI colors, aligned with the main Nord accents.
for index, color in ipairs({
  c.nord1,
  c.nord11,
  c.nord14,
  c.nord13,
  c.nord9,
  c.nord15,
  c.nord8,
  c.nord5,
  c.nord3,
  c.nord11,
  c.nord14,
  c.nord13,
  c.nord9,
  c.nord15,
  c.nord7,
  c.nord6,
}) do
  vim.g['terminal_color_' .. (index - 1)] = color
end

-- Highlight groups are split by editor UI, syntax, Markdown, Treesitter,
-- plugin integrations and LSP/completion UI.
local groups = {
  -- Core editor UI
  Normal = { fg = c.nord4, bg = c.nord0 },
  NormalFloat = { fg = c.nord4, bg = c.nord0 },
  FloatBorder = { fg = c.nord1, bg = c.nord0 },
  FloatTitle = { fg = c.nord14 },
  SignColumn = { fg = c.nord4, bg = c.nord0 },
  EndOfBuffer = { fg = c.nord1 },
  NonText = { fg = c.nord1 },
  Conceal = { fg = c.nord1 },
  Directory = { fg = c.nord7 },
  LineNr = { fg = c.nord2 },
  LineNrAbove = { link = 'LineNr' },
  LineNrBelow = { link = 'LineNr' },
  CursorLineNr = { fg = c.nord3 },
  CursorLine = { bg = c.nord1 },
  CursorColumn = { bg = c.nord1 },
  Cursor = { fg = c.nord0, bg = c.nord8 },
  CursorIM = { fg = c.nord0, bg = c.nord8 },
  TermCursor = { fg = c.nord0, bg = c.nord8 },
  lCursor = { fg = c.nord0, bg = c.nord8 },
  ColorColumn = { bg = c.nord1 },
  VertSplit = { fg = c.nord3_bright, bg = c.nord0 },
  WinSeparator = { fg = c.nord3_bright, bg = c.nord0 },
  Visual = { bg = c.nord2 },
  VisualNOS = { bg = c.nord2 },
  Search = { fg = c.nord6, bg = c.nord10 },
  IncSearch = { fg = c.nord6, bg = c.nord10 },
  CurSearch = { fg = c.nord6, bg = c.nord10 },
  MatchParen = { fg = c.nord15 },
  Folded = { fg = c.nord3_bright, bg = c.none },
  FoldColumn = { fg = c.nord7 },
  Title = { fg = c.nord14 },
  Question = { fg = c.nord14 },
  Error = { fg = c.nord11, underline = true },
  ErrorMsg = { fg = c.nord11 },
  WarningMsg = { fg = c.nord15 },
  MoreMsg = { fg = c.nord4 },
  ModeMsg = { fg = c.nord4 },
  SpecialKey = { fg = c.nord9 },
  Underlined = { fg = c.nord9, underline = true },
  StatusLine = { fg = c.nord4, bg = c.nord2 },
  StatusLineNC = { fg = c.nord4, bg = c.nord1 },
  TabLine = { fg = c.nord4, bg = c.nord1 },
  TabLineFill = { fg = c.nord4, bg = c.none },
  TabLineSel = { fg = c.nord1, bg = c.nord9 },
  WildMenu = { fg = c.nord12 },
  QuickFixLine = { reverse = true },
  qfLineNr = { reverse = true },
  Pmenu = { fg = c.nord4, bg = c.nord0 },
  PmenuSel = { fg = c.nord4, bg = c.nord3 },
  PmenuBorder = { fg = c.nord3, bg = c.nord0 },
  PmenuKind = { fg = c.nord8, bg = c.nord0 },
  PmenuExtra = { fg = c.nord10, bg = c.nord0 },
  PmenuSbar = { bg = c.nord1 },
  PmenuThumb = { bg = c.nord3 },
  SpellBad = { sp = c.nord11, undercurl = true },
  SpellCap = { sp = c.nord7, undercurl = true },
  SpellLocal = { sp = c.nord8, undercurl = true },
  SpellRare = { sp = c.nord9, undercurl = true },
  DiffAdd = { fg = c.nord14, reverse = true },
  DiffChange = { fg = c.nord13, reverse = true },
  DiffDelete = { fg = c.nord11, reverse = true },
  DiffText = { fg = c.nord15, reverse = true },
  YankHighlight = { bg = c.nord10 },
  CursorLineFold = { fg = c.nord7 },
  CursorLineSign = { fg = c.nord4, bg = c.nord1 },

  -- Classic syntax groups
  Comment = { fg = c.nord3_bright },
  Constant = { fg = c.nord4 },
  Character = { fg = c.nord14 },
  Number = { fg = c.nord15 },
  Boolean = { fg = c.nord9 },
  Float = { fg = c.nord15 },
  Identifier = { fg = c.nord9 },
  Function = { fg = c.nord8 },
  Statement = { fg = c.nord9 },
  Conditional = { fg = c.nord9 },
  Repeat = { fg = c.nord9 },
  Label = { fg = c.nord9 },
  Operator = { fg = c.nord9 },
  Keyword = { fg = c.nord9 },
  Exception = { fg = c.nord9 },
  PreProc = { fg = c.nord9 },
  Include = { fg = c.nord9 },
  Define = { fg = c.nord9 },
  Macro = { fg = c.nord9 },
  PreCondit = { fg = c.nord13 },
  Type = { fg = c.nord9 },
  StorageClass = { fg = c.nord9 },
  Structure = { fg = c.nord9 },
  Typedef = { fg = c.nord9 },
  Special = { fg = c.nord4 },
  SpecialChar = { fg = c.nord13 },
  Tag = { fg = c.nord4 },
  Delimiter = { fg = c.nord6 },
  SpecialComment = { fg = c.nord8 },
  Debug = { fg = c.nord11 },
  Ignore = { fg = c.nord1 },
  Todo = { fg = c.nord13 },
  String = { fg = c.nord14 },
  Link = { fg = c.nord9, underline = true },

  -- Legacy Markdown syntax groups
  htmlLink = { link = 'Link' },
  mkdLink = { link = 'Link' },
  markdownLinkText = { link = 'Link' },
  markdownListMarker = { fg = c.nord10 },
  markdownOrderedListMarker = { link = 'markdownListMarker' },
  markdownH1Delimiter = { fg = c.nord11 },
  markdownH2Delimiter = { fg = c.nord12 },
  markdownH3Delimiter = { fg = c.nord13 },
  markdownH1 = { fg = c.nord11 },
  markdownH2 = { fg = c.nord12 },
  markdownH3 = { fg = c.nord13 },
  markdownH4 = { fg = c.nord14 },
  markdownH5 = { fg = c.nord8 },
  markdownH6 = { fg = c.nord15 },
  mkdCodeStart = { fg = c.nord8 },
  mkdCodeEnd = { fg = c.nord8 },

  -- Treesitter captures
  ['@comment'] = { fg = c.nord3_bright },
  ['@comment.note'] = { fg = c.nord10 },
  ['@comment.warning'] = { fg = c.nord15 },
  ['@comment.error'] = { fg = c.nord11 },
  ['@constructor'] = { fg = c.nord9 },
  ['@constant'] = { fg = c.nord13 },
  ['@constant.builtin'] = { fg = c.nord7 },
  ['@constant.macro'] = { fg = c.nord7 },
  ['@attribute'] = { fg = c.nord15 },
  ['@boolean'] = { fg = c.nord9 },
  ['@character'] = { fg = c.nord14 },
  ['@error'] = { fg = c.nord11 },
  ['@exception'] = { fg = c.nord15 },
  ['@float'] = { fg = c.nord15 },
  ['@function'] = { fg = c.nord8 },
  ['@function.call'] = { fg = c.nord8 },
  ['@function.builtin'] = { fg = c.nord8 },
  ['@function.macro'] = { fg = c.nord7 },
  ['@method'] = { fg = c.nord8 },
  ['@function.method'] = { fg = c.nord8 },
  ['@function.method.call'] = { fg = c.nord8 },
  ['@include'] = { fg = c.nord9 },
  ['@label'] = { fg = c.nord15 },
  ['@namespace'] = { fg = c.nord4 },
  ['@number'] = { fg = c.nord15 },
  ['@operator'] = { fg = c.nord9 },
  ['@parameter'] = { fg = c.nord10 },
  ['@property'] = { fg = c.nord10 },
  ['@field'] = { fg = c.nord4 },
  ['@punctuation.delimiter'] = { fg = c.nord8 },
  ['@punctuation.bracket'] = { fg = c.nord8 },
  ['@punctuation.special'] = { fg = c.nord8 },
  ['@repeat'] = { fg = c.nord9 },
  ['@string'] = { fg = c.nord14 },
  ['@string.escape'] = { fg = c.nord15 },
  ['@string.regex'] = { fg = c.nord7 },
  ['@string.special'] = { fg = c.nord13 },
  ['@symbol'] = { fg = c.nord15 },
  ['@type'] = { fg = c.nord9 },
  ['@type.builtin'] = { fg = c.nord9 },
  ['@variable'] = { fg = c.nord4 },
  ['@variable.builtin'] = { fg = c.nord4 },
  ['@variable.global'] = { fg = c.nord4 },
  ['@conditional'] = { fg = c.nord9 },
  ['@keyword'] = { fg = c.nord9 },
  ['@keyword.function'] = { fg = c.nord8 },
  ['@keyword.return'] = { fg = c.nord8 },
  ['@keyword.operator'] = { fg = c.nord8 },
  ['@tag'] = { fg = c.nord4 },
  ['@tag.attribute'] = { fg = c.nord15 },
  ['@tag.delimiter'] = { fg = c.nord15 },
  ['@markup.list'] = { fg = c.nord10 },
  ['@markup.list.checked'] = { fg = c.nord10 },
  ['@markup.list.unchecked'] = { fg = c.nord10 },
  ['@markup.link'] = { fg = c.nord9, underline = true },
  ['@markup.link.label'] = { fg = c.nord9, underline = true },
  ['@markup.link.url'] = { fg = c.nord9, underline = true },
  ['@markup.raw'] = { fg = c.nord9, bg = c.nord1 },
  ['@markup.raw.block'] = { bg = c.nord1 },
  ['@markup.heading.1'] = { fg = c.nord11 },
  ['@markup.heading.2'] = { fg = c.nord12 },
  ['@markup.heading.3'] = { fg = c.nord13 },
  ['@markup.heading.4'] = { fg = c.nord14 },
  ['@markup.heading.5'] = { fg = c.nord8 },
  ['@markup.heading.6'] = { fg = c.nord15 },
  ['@markup.heading.1.delimiter'] = { fg = c.nord11 },
  ['@markup.heading.2.delimiter'] = { fg = c.nord12 },
  ['@markup.heading.3.delimiter'] = { fg = c.nord13 },
  ['@markup.heading.4.delimiter'] = { fg = c.nord14 },
  ['@markup.heading.5.delimiter'] = { fg = c.nord8 },
  ['@markup.heading.6.delimiter'] = { fg = c.nord15 },

  -- Markview.nvim, mirrored from the Markdown heading/list/link/code palette.
  MarkviewPalette0 = { fg = c.nord3_bright, bg = c.none },
  MarkviewPalette0Fg = { fg = c.nord3_bright },
  MarkviewPalette0Bg = { bg = c.none },
  MarkviewPalette0Sign = { fg = c.nord3_bright },
  MarkviewPalette1 = { fg = c.nord11, bg = c.none },
  MarkviewPalette1Fg = { fg = c.nord11 },
  MarkviewPalette1Bg = { bg = c.none },
  MarkviewPalette1Sign = { fg = c.nord11 },
  MarkviewPalette2 = { fg = c.nord12, bg = c.none },
  MarkviewPalette2Fg = { fg = c.nord12 },
  MarkviewPalette2Bg = { bg = c.none },
  MarkviewPalette2Sign = { fg = c.nord12 },
  MarkviewPalette3 = { fg = c.nord13, bg = c.none },
  MarkviewPalette3Fg = { fg = c.nord13 },
  MarkviewPalette3Bg = { bg = c.none },
  MarkviewPalette3Sign = { fg = c.nord13 },
  MarkviewPalette4 = { fg = c.nord14, bg = c.none },
  MarkviewPalette4Fg = { fg = c.nord14 },
  MarkviewPalette4Bg = { bg = c.none },
  MarkviewPalette4Sign = { fg = c.nord14 },
  MarkviewPalette5 = { fg = c.nord8, bg = c.none },
  MarkviewPalette5Fg = { fg = c.nord8 },
  MarkviewPalette5Bg = { bg = c.none },
  MarkviewPalette5Sign = { fg = c.nord8 },
  MarkviewPalette6 = { fg = c.nord15, bg = c.none },
  MarkviewPalette6Fg = { fg = c.nord15 },
  MarkviewPalette6Bg = { bg = c.none },
  MarkviewPalette6Sign = { fg = c.nord15 },
  MarkviewPalette7 = { fg = c.nord9, bg = c.none },
  MarkviewPalette7Fg = { fg = c.nord9 },
  MarkviewPalette7Bg = { bg = c.none },
  MarkviewPalette7Sign = { fg = c.nord9 },
  MarkviewCode = { bg = c.nord1 },
  MarkviewCodeFg = { fg = c.nord1 },
  MarkviewCodeInfo = { fg = c.nord3_bright, bg = c.nord1 },
  MarkviewInlineCode = { fg = c.nord9, bg = c.nord1 },
  MarkviewBlockQuoteDefault = { link = 'MarkviewPalette0Fg' },
  MarkviewBlockQuoteError = { link = 'MarkviewPalette1Fg' },
  MarkviewBlockQuoteNote = { link = 'MarkviewPalette5Fg' },
  MarkviewBlockQuoteOk = { link = 'MarkviewPalette4Fg' },
  MarkviewBlockQuoteSpecial = { link = 'MarkviewPalette3Fg' },
  MarkviewBlockQuoteWarn = { link = 'MarkviewPalette2Fg' },
  MarkviewCheckboxCancelled = { link = 'MarkviewPalette0Fg' },
  MarkviewCheckboxChecked = { link = 'MarkviewPalette4Fg' },
  MarkviewCheckboxPending = { link = 'MarkviewPalette2Fg' },
  MarkviewCheckboxProgress = { link = 'MarkviewPalette6Fg' },
  MarkviewCheckboxUnchecked = { link = 'MarkviewPalette1Fg' },
  MarkviewCheckboxStriked = { fg = c.nord3_bright, strikethrough = true },
  MarkviewIcon0 = { fg = c.nord3_bright, bg = c.nord1 },
  MarkviewIcon1 = { fg = c.nord11, bg = c.nord1 },
  MarkviewIcon2 = { fg = c.nord12, bg = c.nord1 },
  MarkviewIcon3 = { fg = c.nord13, bg = c.nord1 },
  MarkviewIcon4 = { fg = c.nord14, bg = c.nord1 },
  MarkviewIcon5 = { fg = c.nord8, bg = c.nord1 },
  MarkviewIcon6 = { fg = c.nord15, bg = c.nord1 },
  MarkviewHeading1 = { link = 'MarkviewPalette1' },
  MarkviewHeading2 = { link = 'MarkviewPalette2' },
  MarkviewHeading3 = { link = 'MarkviewPalette3' },
  MarkviewHeading4 = { link = 'MarkviewPalette4' },
  MarkviewHeading5 = { link = 'MarkviewPalette5' },
  MarkviewHeading6 = { link = 'MarkviewPalette6' },
  MarkviewHeading1Sign = { link = 'MarkviewPalette1Sign' },
  MarkviewHeading2Sign = { link = 'MarkviewPalette2Sign' },
  MarkviewHeading3Sign = { link = 'MarkviewPalette3Sign' },
  MarkviewHeading4Sign = { link = 'MarkviewPalette4Sign' },
  MarkviewHeading5Sign = { link = 'MarkviewPalette5Sign' },
  MarkviewHeading6Sign = { link = 'MarkviewPalette6Sign' },
  MarkviewHyperlink = { link = 'Link' },
  MarkviewImage = { link = 'Link' },
  MarkviewEmail = { link = 'Link' },
  MarkviewSubscript = { link = 'MarkviewPalette3Fg' },
  MarkviewSuperscript = { link = 'MarkviewPalette6Fg' },
  MarkviewListItemMinus = { link = 'markdownListMarker' },
  MarkviewListItemPlus = { link = 'markdownListMarker' },
  MarkviewListItemStar = { link = 'markdownListMarker' },
  MarkviewTableHeader = { link = '@markup.heading.3' },
  MarkviewTableBorder = { fg = c.nord8 },
  MarkviewTableAlignLeft = { link = '@markup.heading.3' },
  MarkviewTableAlignCenter = { link = '@markup.heading.3' },
  MarkviewTableAlignRight = { link = '@markup.heading.3' },

  -- Legacy Treesitter group aliases
  TSComment = { link = '@comment' },
  TSString = { link = '@string' },
  TSCharacter = { link = '@character' },
  TSNumber = { link = '@number' },
  TSFloat = { link = '@float' },
  TSBoolean = { link = '@boolean' },
  TSVariable = { link = '@variable' },
  TSVariableBuiltin = { link = '@variable.builtin' },
  TSParameter = { link = '@parameter' },
  TSField = { link = '@field' },
  TSProperty = { link = '@property' },
  TSFunction = { link = '@function' },
  TSMethod = { link = '@method' },
  TSFuncBuiltin = { link = '@function.builtin' },
  TSFuncMacro = { link = '@function.macro' },
  TSConstructor = { link = '@constructor' },
  TSConditional = { link = '@conditional' },
  TSRepeat = { link = '@repeat' },
  TSKeyword = { link = '@keyword' },
  TSKeywordFunction = { link = '@keyword.function' },
  TSKeywordReturn = { link = '@keyword.return' },
  TSKeywordOperator = { link = '@keyword.operator' },
  TSOperator = { link = '@operator' },
  TSType = { link = '@type' },
  TSTypeBuiltin = { link = '@type.builtin' },
  TSNamespace = { link = '@namespace' },
  TSLabel = { link = '@label' },
  TSPunctDelimiter = { link = '@punctuation.delimiter' },
  TSPunctBracket = { link = '@punctuation.bracket' },
  TSPunctSpecial = { link = '@punctuation.special' },

  -- Filetype-specific compatibility groups
  yamlBlockMappingKey = { fg = c.nord7 },
  yamlBool = { link = 'Boolean' },
  yamlDocumentStart = { link = 'Keyword' },
  yamlTSField = { fg = c.nord7 },
  yamlTSString = { fg = c.nord4 },
  yamlTSPunctSpecial = { link = 'Keyword' },
  yamlKey = { fg = c.nord7 },

  -- LSP references and diagnostics
  LspReferenceText = { fg = c.nord4, bg = c.nord1 },
  LspReferenceRead = { fg = c.nord4, bg = c.nord1 },
  LspReferenceWrite = { fg = c.nord4, bg = c.nord1 },
  DiagnosticError = { fg = c.nord11 },
  DiagnosticWarn = { fg = c.nord15 },
  DiagnosticInfo = { fg = c.nord10 },
  DiagnosticHint = { fg = c.nord9 },
  DiagnosticSignError = { fg = c.nord11 },
  DiagnosticSignWarn = { fg = c.nord15 },
  DiagnosticSignInfo = { fg = c.nord10 },
  DiagnosticSignHint = { fg = c.nord9 },
  DiagnosticFloatingError = { fg = c.nord11 },
  DiagnosticFloatingWarn = { fg = c.nord15 },
  DiagnosticFloatingInfo = { fg = c.nord10 },
  DiagnosticFloatingHint = { fg = c.nord9 },
  DiagnosticUnderlineError = { sp = c.nord11, undercurl = true },
  DiagnosticUnderlineWarn = { sp = c.nord15, undercurl = true },
  DiagnosticUnderlineInfo = { sp = c.nord10, undercurl = true },
  DiagnosticUnderlineHint = { sp = c.nord10, undercurl = true },
  LspInlayHint = { fg = c.inlay_hint },
  LspCodeLens = { fg = c.inlay_hint },
  LspSignatureActiveParameter = { underline = true, sp = c.nord4 },
  DiagnosticDeprecated = { strikethrough = true, fg = c.nord3_bright },
  DiagnosticUnnecessary = { fg = c.nord3_bright },

  -- blink.cmp
  BlinkCmpLabel = { fg = c.nord4 },
  BlinkCmpLabelDeprecated = { fg = c.nord3_bright, strikethrough = true },
  BlinkCmpLabelMatch = { fg = c.nord9 },
  BlinkCmpLabelDetail = { link = 'PmenuExtra' },
  BlinkCmpLabelDescription = { link = 'Comment' },
  BlinkCmpMenu = { fg = c.nord4, bg = c.nord0 },
  BlinkCmpMenuBorder = { fg = c.nord3, bg = c.nord0 },
  BlinkCmpMenuSelection = { bg = c.nord3 },
  BlinkCmpDoc = { fg = c.nord4, bg = c.nord0 },
  BlinkCmpDocBorder = { fg = c.nord3, bg = c.nord0 },
  BlinkCmpSignatureHelpBorder = { fg = c.nord3, bg = c.nord0 },
  BlinkCmpGhostText = { fg = c.inlay_hint },
  BlinkCmpKind = { link = 'PmenuKind' },
  BlinkCmpSource = { link = 'PmenuExtra' },
  BlinkCmpKindText = { link = 'BlinkCmpKind' },
  BlinkCmpKindMethod = { link = 'BlinkCmpKind' },
  BlinkCmpKindFunction = { link = 'BlinkCmpKind' },
  BlinkCmpKindConstructor = { link = 'BlinkCmpKind' },
  BlinkCmpKindField = { link = 'BlinkCmpKind' },
  BlinkCmpKindVariable = { link = 'BlinkCmpKind' },
  BlinkCmpKindClass = { link = 'BlinkCmpKind' },
  BlinkCmpKindInterface = { link = 'BlinkCmpKind' },
  BlinkCmpKindModule = { link = 'BlinkCmpKind' },
  BlinkCmpKindProperty = { link = 'BlinkCmpKind' },
  BlinkCmpKindUnit = { link = 'BlinkCmpKind' },
  BlinkCmpKindValue = { link = 'BlinkCmpKind' },
  BlinkCmpKindEnum = { link = 'BlinkCmpKind' },
  BlinkCmpKindKeyword = { link = 'BlinkCmpKind' },
  BlinkCmpKindSnippet = { link = 'BlinkCmpKind' },
  BlinkCmpKindColor = { link = 'BlinkCmpKind' },
  BlinkCmpKindFile = { link = 'BlinkCmpKind' },
  BlinkCmpKindReference = { link = 'BlinkCmpKind' },
  BlinkCmpKindFolder = { link = 'BlinkCmpKind' },
  BlinkCmpKindEnumMember = { link = 'BlinkCmpKind' },
  BlinkCmpKindConstant = { link = 'BlinkCmpKind' },
  BlinkCmpKindStruct = { link = 'BlinkCmpKind' },
  BlinkCmpKindEvent = { link = 'BlinkCmpKind' },
  BlinkCmpKindOperator = { link = 'BlinkCmpKind' },
  BlinkCmpKindTypeParameter = { link = 'BlinkCmpKind' },
}

-- Apply all highlight groups after the full table is built.
for group, spec in pairs(groups) do
  set(group, spec)
end
