fork = false
frame = "none"
idle = true
maximized = true
mouse-cursor-icon = "arrow"
no-multigrid = false
srgb = true
tabs = false
system-pinned-hotkey = ""
system-switcher-hotkey = ""
system-new-window-hotkey = ""
system-hide-hotkey = ""
system-hide-others-hotkey = ""
system-quit-hotkey = ""
system-minimize-hotkey = ""
system-fullscreen-hotkey = ""
system-show-all-tabs-hotkey = ""
system-tab-prev-hotkey = ""
system-tab-next-hotkey = ""
title-hidden = true
vsync = true

[font]
normal = ["JetBrainsMono Nerd Font Mono"]
size = 22

[box-drawing]
mode = "native"
