set -g prefix C-Space
unbind C-b
bind -n C-b last-window
bind B set -g status
bind c new-window -c "#{pane_current_path}"

set -sg escape-time 0
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB:usstyle"
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
set -g history-limit 10000
setw -g mode-keys vi
set-option -g focus-events on

set -g status-style "fg=#D8DEE9,bg=#3b4252"
set-option -g status-right ""
set -g status off
