# ─── Terminal ────────────────────────────────────────────────────────────────

set -as terminal-features ',*:RGB'
set -g focus-events on
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

set -s extended-keys on
set -as terminal-features ',*:extkeys'

# ─── Nummering ───────────────────────────────────────────────────────────────

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# ─── Nieuw venster en splits erven de huidige map ────────────────────────────

bind c new-window -c '#{pane_current_path}'
bind '"' split-window -c '#{pane_current_path}'
bind % split-window -h -c '#{pane_current_path}'

# ─── Statusbalk ──────────────────────────────────────────────────────────────

set -g status-position top
set -g status-justify right
set -g status-style 'bg=#2e3440 fg=#4C566A'

set -g status-left ''
set -g status-right ' [#{session_name}] '
